#!/usr/bin/env python
'''
	RABBITFOOT 
	a hand tool for testing RabbitMQ (AMQP) systems
	Version 0.2

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see http://www.gnu.org/licenses/.
'''
import pika, os, logging, sys, getopt
logging.basicConfig()

# Parse CLODUAMQP_URL (fallback to localhost)

default_server  = "localhost"
default_user = "guest"
default_password = "guest"
default_vhost = "" #default_user
default_port = "5672"
default_queue = "DEMO"
default_message ="Ding!"
default_timeout = 5
default_is_sender = True
default_is_getter = False


def usage():
    print 'rabbitfoot [--sender(-S)/--receiver(-R)/--getter(G)] [-s <server>] [-p <port>] [-u <user>] [-w <password>] [-v <vhost>] [-q <queue>] [-m <message>] [-t <timeout>]'
    print "hint: you can also use long options - it's just the name of the field with -- before it: --port <port>, --password <password>, etc. "
    sys.exit()

# create a function which is called on incoming messages
def callback(ch, method, properties, body):
    handleBody(body)

def handleBody(body):
    print " [x] Received %r" % (body)

def run(isSender, isGetter, server, user, password, vhost, port, queue, message,timeout):
    if (isSender is None):
        isSender = default_is_sender
    if (isGetter is None):
        isGetter = default_is_getter
    if (server is None):
        server = default_server
    if (user is None):
        user = default_user
    if (vhost is None):
        vhost = default_vhost
    if (password is None):
        password = default_password
    if (port is None):
        port = default_port
    if (queue is None):
        queue = default_queue
    if (message is None):
        message = default_message
    if (timeout is None):
        timeout = default_timeout

    
    ampq_url = "ampq://%s:%s@%s:%s/%s" % (user,password,server,port,vhost)
    
    url = os.environ.get('CLOUDAMQP_URL',ampq_url)


    params = pika.URLParameters(url)
    params.socket_timeout = timeout
    connection = pika.BlockingConnection(params) # Connect to CloudAMQP
    channel = connection.channel() # start a channel



    channel.queue_declare(queue,durable=True) # Declare a queue


    if (isSender) :
        # send a message
        channel.basic_publish(exchange='', 
                              routing_key=queue, 
                              body=message,
                              properties=pika.BasicProperties(
                                  delivery_mode = 2, # make message persistent
                              ))
        print "Sender: Produced message: %s" % message
    else :
        if (isGetter) :
            print "Getter: getting a message"


            method_frame, header_frame, body = channel.basic_get(queue = queue)
            if method_frame == None :                
                print "Queue Empty.."
            else:            
                channel.basic_ack(delivery_tag=method_frame.delivery_tag)
                handleBody(body)
        else:
            print "Receiver: starting to consume messeges (Ctrl+C to exit)"
            # set up subscription on the queue
            channel.basic_consume(callback,
                                  queue,
                                  no_ack=True)
            channel.start_consuming() # start consuming (blocks)
        
        #anyhow..
        connection.close()

	
def main(argv):
    try:
        opts, args = getopt.getopt(argv,"SRGhs:u:w:p:v:q:m:t:",["receiver","sender","getter","server=","user=","password=","vohst=","port=","queue=","message=","timeout="])
    except getopt.GetoptError:
        usage()    

    isSender = isGetter = server = user = password = vhost = port = queue = message = timeout = None

    for opt, arg in opts:
        if opt == '-h':
            usage()
        elif opt in ("-S", "--sender"):
            isSender  = True
        elif opt in ("-R", "--receiver"):
            isSender  = False
            isGetter  = False
        elif opt in ("-G", "--getter"):
            isSender  = False
            isGetter  = True   
        elif opt in ("-s", "--server"):
            server = arg
        elif opt in ("-u", "--user"):
            user = arg
        elif opt in ("-w", "--password"):
            password = arg
        elif opt in ("-p", "--port"):
            port = arg
        elif opt in ("-v", "--vhost"):
            vhost = arg
        elif opt in ("-q", "--queue"):
            queue = arg
        elif opt in ("-m", "--message"):
            message = arg
        elif opt in ("-t", "--timeout"):
            timeout = arg



    run(isSender,isGetter,server,user,password,vhost,port,queue,message,timeout)

        
        

if __name__ == "__main__":
    main(sys.argv[1:])
    


